# Generated by Django 5.0.2 on 2024-02-29 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bugdata_bugreviewer_projectdetail_llmdata_chatdata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetail',
            name='project_u_n',
        ),
    ]
