# Generated by Django 5.0.2 on 2024-03-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_projectdetail_project_u_n'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='ann_to',
        ),
        migrations.AddField(
            model_name='bugdata',
            name='bu_created_time',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sprintdata',
            name='sp_created_time',
            field=models.CharField(default='', max_length=20),
        ),
    ]
