# Generated by Django 5.0.2 on 2024-03-03 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_announcement_ann_to_bugdata_bu_created_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugreviewer',
            name='bug',
        ),
        migrations.DeleteModel(
            name='BugData',
        ),
        migrations.DeleteModel(
            name='BugReviewer',
        ),
    ]
