# Generated by Django 5.0.2 on 2024-03-03 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_bugreviewer_bug_delete_bugdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_title', models.CharField(max_length=200)),
                ('bug_detail', models.TextField()),
                ('bu_created_time', models.CharField(default='', max_length=20)),
                ('deadline_time', models.CharField(max_length=20)),
                ('submitted_time', models.CharField(max_length=20)),
                ('bug_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_from_user', to='home.userdetail')),
                ('bug_reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.reportbug')),
                ('bug_reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_reviewer_user', to='home.userdetail')),
                ('bug_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_to_user', to='home.userdetail')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.projectdetail')),
            ],
        ),
        migrations.CreateModel(
            name='BugReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=20)),
                ('dAndTime', models.CharField(max_length=20)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bugdata')),
            ],
        ),
    ]
