# Generated by Django 5.0.2 on 2024-04-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_bugdata_bugreviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportbug',
            name='addressed',
            field=models.TextField(default='', max_length=5),
        ),
    ]
