# Generated by Django 5.0.2 on 2024-04-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_reportbug_addressed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugdata',
            name='rev_sub_time',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bugdata',
            name='review',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sprintdata',
            name='rev_sub_time',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sprintdata',
            name='review',
            field=models.CharField(default='', max_length=20),
        ),
    ]
